### ISSUE TITLE
Add Suggestion

### ISSUE THREAD

**Issue by ghost** [ChessMax/awesome-game-engines#4]
OpenMW Engine, open-source engine drop-in replacement for Bethesda morrowind engine. Also, alot of games by Id software had their engines open-source like wolfenstein 3d and quake. There is some attempt for doing some of the other elder scroll games, but they are not at a very useful stage.

**Comment by ChessMax** [comment]
> Also, alot of games by Id software had their engines open-source like wolfenstein 3d and quake.

Yea, but is there a reason to use them today? It seems that they are too outdated?

**Comment by ghost** [comment]
OpenMW is still being perfected, it provide better visuals than the original, but as for the ones by I'd software, mainly for people who want to make retro games. If this repo is more towards modern engines, I'll name sure to suggest ones that fall into that category

**Comment by ChessMax** [comment]
If you think that this list benefits from adding Id's software engine(s), then let's add them. Please, provider a link and description at least. Better if you open MR.

**Comment by ghost** [comment]
I think you are right on not including ID software(s) engines, since I was just thinking, although stuff like collosal cave adventure, Zork, quake, doom, are cool things to look at and maybe play with, but how many would actually look at the code and modify it. It does fall under the obscure part but yeah you're right, most people look more modern things that are being kept uptodate. But I think OpenMW would be a good add. I can make a PR if you'd like for OpenMW, make a description, and have link to it's website

**Comment by ChessMax** [comment]
> I can make a PR if you'd like for OpenMW, make a description, and have link to it's website

I've already added it. That's why the issue is closed since that moment. Thanks!

**Comment by ghost** [comment]
You're welcome! Thank you!
